<?php
if ($savemodule){
	$completecode = str_replace("\n","<br />", $completecode);
	$fgc = file_get_contents("./modules/modulebuilder/savedmodules/{$session['user']['acctid']}.txt");
	$user_savedmodules = unserialize($fgc);
	$user_savedmodules[$op][$modulename] = $completecode;
	$f = fopen("./modules/modulebuilder/savedmodules/{$session['user']['acctid']}.txt","w+");
	fwrite($f,serialize($user_savedmodules));
	fclose($f);
	
	$fgd = file_get_contents("./modules/modulebuilder/savedmodules/{$session['user']['acctid']}_vals.txt");
	$user_post = unserialize($fgd);
	$user_post[$op][$modulename] = $_POST;
	unset($user_post[$op][$modulename]['savemodule']);
	unset($user_post[$op][$modulename]['completecode']);
	$f = fopen("./modules/modulebuilder/savedmodules/{$session['user']['acctid']}_vals.txt","w+");
	fwrite($f,serialize($user_post));
	fclose($f);
	
	output("`@`bSAVED!`b`0`n");
}
if ($modulesubmit == ""){
	if ($hostscript == "") $hostscript = "haberdasher";
	if ($hostscriptver == "") $hostscriptver = "2.5";
	if ($hostscriptinfo == "") $hostscriptinfo = "core distrobution";
	if ($questlongtitle == "") $questlongtitle = "Your Big Adventure";
	if ($queststep0mess == "") $queststep0mess = "- the adventure of a lifetime -";
	if ($queststoryp1 == "") $queststoryp1 = "This is an event that introduces the quest and sets things in motion.";
	if ($queststep1mess == "") $queststep1mess = "Our hero has begun his/her quest.";
	if ($queststoryp2 == "") $queststoryp2 = "This text will be show after clicking a nav from the host module. It is the second step in the quest... Generally a player will be given something or some information that allows them to then go on to the third part of the quest.";
	if ($queststep2mess == "") $queststep2mess = "Our hero has completed the second step.";
	if ($questnavp2 == "") $questnavp2 = "Do Something.";
	if ($queststoryp3 == "") $queststoryp3 = "This is your next event... you will find something... encounter something etc... the event will give you one last task at the host module... usually bringing the item or info you have attained back to the character at the host module.";
	if ($queststep3mess == "") $queststep3mess = "Our hero has completed step 3";
	if ($queststoryp4 == "") $queststoryp4 = "The final encounter with the host modules character.. this character now gives you what you need to complete the last step of your quest.";
	if ($queststep4mess == "") $queststep4mess = "Our hero has completed step 4 of the quest!";
	if ($questnavp4 == "") $questnavp4 = "Give Joe the Beans.";
	if ($queststoryend == "") $queststoryend = "And finally.. you have completed your quest and all is well.... you are rewarded for a job well done.";
	if ($questsuccessmess == "") $questsuccessmess = "Our hero has completed the quest!";
	if ($questfailmess == "") $questfailmess = "Our hero has failed to complete the quest.";
	rawoutput("<form method='post' action='runmodule.php?module=modulebuilder&op=quest' name='questbuilder'>");
	rawoutput("<small style='font-style: italic;'>Module name should contain no spaces!</small><br>");
	rawoutput("Module Name: <input value = '".$modulename."' size='20' name='modulename'><br>");
	rawoutput("Module Title: <input value = '".$moduletitle."' size='25' name='moduletitle'><br>");
	rawoutput("<small style='font-style: italic;'>This is a script to tie this to (such as Deimos'Haberdashery).</small><br>");
	rawoutput("Host Script: <input value='".$hostscript."' size='20' name='hostscript'><br>");
	rawoutput("Host Script Ver: <input value='".$hostscriptver."' size='6' name='hostscriptver'><br>");
	rawoutput("Host Script Info: <input value='".$hostscriptinfo."' size='50' name='hostscriptinfo'><br><br>");
	rawoutput("<small style='font-style: italic;'>long title appears as the header when running the module.</small><br>");
	rawoutput("Quest Long Title: <input value='".$questlongtitle."' size='60' name='questlongtitle'><br>");
	rawoutput("<small style='font-style: italic;'>intro message annotates the stage the player is at. </small><br>");
	rawoutput("Quest Intro Message: <input value='".$queststep0mess."' size='60' name='queststep0mess'><br><br>");
	rawoutput("Quest Part 1 (and Final) Event Type: <select name='questevent1'><option value='forest'>Forest</option><option value='village'>Village</option></select><br>");
	rawoutput("Quest Story Part 1: <br><textarea class='input' cols='60' rows='10' name='queststoryp1'>".$queststoryp1."</textarea><br>");
	rawoutput("Quest 1st step Message: <input value='".$queststep1mess."' size='60' name='queststep1mess'><br><br>");
	rawoutput("Quest Story Part 2:<br><textarea class='input' cols='60' rows='10' name='queststoryp2'>".$queststoryp2."</textarea><br>");
	rawoutput("Quest 2nd step Message: <input value='".$queststep2mess."' size='60' name='queststep2mess'><br>");
	rawoutput("<small style='font-style: italic;'>describe what is to be done with the nav (ex. &nbsp;Ask about beans).</small><br>");
	rawoutput("Quest Story Part 2 Nav: <input name='questnavp2' value='".$questnavp2."'><br><br>");
	rawoutput("Quest Part 3 Event Type: <select name='questevent3'><option value='forest'>Forest</option><option value='village'>Village</option><option value='travel'>Travel</option></select><br>");
	rawoutput("Quest Story Part 3:<br><textarea class='input' cols='60' rows='10' name='queststoryp3'>".$queststoryp3."</textarea><br>");
	rawoutput("Quest 3rd step Message: <input value='".$queststep3mess."' size='60' name='queststep3mess'><br><br>");
	rawoutput("Quest Story Part 4:<br><textarea class='input' cols='60' rows='10' name='queststoryp4'>".$queststoryp4."</textarea><br>");
	rawoutput("Quest 4th step Message: <input value='".$queststep4mess."' size='60' name='queststep4mess'><br>");
	rawoutput("Quest Story Part 4 Nav: <input name='questnavp4' value='".$questnavp4."'><br><br>");
	rawoutput("Quest Story End: <br><textarea class='input' cols='60' rows='10' name='queststoryend'>".$queststoryend."</textarea><br>");
	rawoutput("Quest Success Message: <input value='".$questsuccessmess."' size='60' name='questsuccessmess'><br><br>");
	rawoutput("Quest Failure Message: <input value='".$questfailmess."' size='60' name='questfailmess'><br><br><br>");
	rawoutput("<input type='hidden' name='modulesubmit' value='done'> ");
	rawoutput("<input name='Submit' value='Submit' type='submit'></form>");
	addnav("","runmodule.php?module=modulebuilder&op=quest");
}else{
$code = "require_once(\"lib/villagenav.php\");\n";
$code .= "require_once(\"lib/quests.php\");\n";
$code .= "\n";
$code .= "function quest_".$modulename."_getmoduleinfo(){\n";
$code .= "	\$info = array(\n";
$code .= "		\"name\"=>\"Quest - ".$moduletitle."\",\n";
$code .= "		\"version\"=>\"1.0\",\n";
$code .= "		\"author\" => \"".get_module_pref("author")." - Built with Module Builder by `3Lonny Luberts`0\",\n";
$code .= "		\"category\"=>\"Quest\",\n";
$code .= "		\"download\" => \"".get_module_pref("downloc")."specialty_".$modulename.".zip\",\n";
$code .= "		\"vertxtloc\"=>\"".get_module_pref("vertxtloc")."\",\n";
$code .= "		\"requires\"=>array(\n";
$code .= "			\"questbasics\" => \"1.0|XChrisX, http://beta.lotgd.de/downloads/questpack.zip\",\n";
$code .= "			\"cities\" => \"1.0|Eric Stevens, core_module\",\n";
$code .= "			\"".$hostscript."\" => \"".$hostscriptver."|".$hostscriptinfo."\",\n";
$code .= "			),\n";
$code .= "		\"settings\"=>array(\n";
$code .= "			\"questloc\"=>\"Where is the host module located?,location|\".getsetting(\"villagename\", LOCATION_FIELDS),\n";
$code .= "			\"req_min_hw\" => \"Required Hero Points to receive the quest, int|5\",\n";
$code .= "			\"req_max_hw\" => \"Maximum Hero Points to receive the quest, int|10\",\n";
$code .= "			\"req_min_dk\" => \"Required Dragon Kills to receive the quest, int|0\",\n";
$code .= "			\"req_max_dk\" => \"Maximum Dragon Kills to receive the quest, int|0\",\n";
$code .= "			\"req_min_lev\" => \"Minimum level to receive the quest, int|1\",\n";
$code .= "			\"req_max_lev\" => \"Maximum level to receive the quest, int|2\",\n";
$code .= "			\"req_quest\" => \"Is another quest required before starting this quest?, string|\",\n";
$code .= "			\"req_superuser\" => \"Can the quest be done by superusers at any time?, bool|true\",\n";
$code .= "			\"reward_exp\" => \"Reward (Experience), int|1000\",\n";
$code .= "			\"reward_explevel\" => \"Additional experience points per level, int|50\",\n";
$code .= "			\"reward_gems\" => \"Reward (Gems), int|1\",\n";
$code .= "			\"reward_gold\" => \"Reward (Gold), int|500\",\n";
$code .= "			\"reward_goldlevel\" => \"Additional gold per level, int|75\",\n";
$code .= "			\"reward_quest\" => \"Number of quest points the player receives?, int|50\",\n";
$code .= "		),\n";
$code .= "		\"prefs\" => array(\n";
$code .= "			\"queststarted\" => \"Has the player accepted the quest?, bool|false\",\n";
$code .= "			\"queststation\" => \"What point in the quest is the player at?, int|0\",\n";
$code .= "		),\n";
$code .= "	);\n";
$code .= "	return \$info;\n";
$code .= "}\n";
$code .= "\n";
$code .= "function quest_".$modulename."_chance(\$where){\n";
$code .= "	global \$session;\n";
$code .= "	\$queststation = get_module_pref(\"queststation\", \"quest_".$modulename."\");\n";
$code .= "	if (requirements_met(\"quest_".$modulename."\") || get_module_pref(\"queststarted\", \"quest_".$modulename."\")) {\n";
$code .= "		if (\$where == \"".$questevent1."\") {\n";
                                    $code .= "if ((\$queststation == 0 || \$queststation == 4) && \$session['user']['location'] == get_module_setting(\"questloc\")) {\n";
$code .= "				\$encounter = 50;\n";
$code .= "			}elseif (\$where == \"".$questevent3."\" && \$queststation == 2){\n";
$code .= "				\$encounter = 100;\n";
$code .= "			}\n";
$code .= "		} else if (\$where == \"".$questevent3."\" && \$queststation == 2) {\n";
$code .= "			\$encounter = 100;\n";
$code .= "		} else {\n";
$code .= "			\$encounter = 0;\n";
$code .= "		}\n";
$code .= "		return \$encounter;\n";
$code .= "	} else {\n";
$code .= "		return 0;\n";
$code .= "	}\n";
$code .= "}\n";
$code .= "\n";
$code .= "function quest_".$modulename."_install() {\n";
$code .= "\n";
$code .= "	\$station = array(\n";
$code .= "		\"-2\" => \"`\ ".$questfailmess." `0\",\n";
$code .= "		\"-1\" => \"`@ ".$questsuccessmess." `0\",\n";
$code .= "		\"0\" => \"`6 ".$queststep0mess." `0\",\n";
$code .= "		\"1\" => \"`6 ".$queststep1mess." `0\",\n";
$code .= "		\"2\" => \"`6 ".$queststep2mess." `0\",\n";
$code .= "		\"3\" => \"`6 ".$queststep3mess." `0\",\n";
$code .= "		\"4\" => \"`6 ".$queststep4mess." `0\",\n";
$code .= "	);\n";
$code .= "	\$questfilename = \"quest_".$modulename."\";\n";
$code .= "	db_query(\"DELETE FROM quests WHERE questname = '\".\$questfilename.\"'\");\n";
$code .= "	foreach(\$station as \$outputstation => \$entry) {\n";
$code .= "		\$sql = \"INSERT INTO quests (questname, queststation, questdescription) VALUES ('\".\$questfilename.\"', '\".\$outputstation.\"', '\".\$entry.\"')\";\n";
$code .= "		db_query(\$sql);\n";
$code .= "	}\n";
$code .= "\n";
$code .= "	module_addeventhook(\"village\", \"require_once(*Q*modules/quest_".$modulename.".php*Q*); return quest_".$modulename."_chance(*Q*village*Q*);\");\n";
$code .= "	module_addeventhook(\"forest\", \"require_once(*Q*modules/quest_".$modulename.".php*Q*); return quest_".$modulename."_chance(*Q*forest*Q*);\");\n";
$code .= "	module_addeventhook(\"travel\", \"require_once(*Q*modules/quest_".$modulename.".php*Q*); return quest_".$modulename."_chance(*Q*travel*Q*);\");\n";
$code .= "	module_addhook(\"footer-runmodule\");\n";
$code .= "	return true;\n";
$code .= "}\n";
$code .= "\n";
$code .= "function quest_".$modulename."_uninstall(){\n";
$code .= "	return true;\n";
$code .= "}\n";
$code .= "\n";
$code .= "function quest_".$modulename."_dohook(\$hookname,\$args) {\n";
$code .= "	global \$session, \$SCRIPT_NAME;\n";
$code .= "	\$script = substr(\$SCRIPT_NAME,0,strpos(\$SCRIPT_NAME,\".\"));\n";
$code .= "	if (\$script == \"runmodule\") \$script = httpget('module');\n";
$code .= "	\$queststation = get_module_pref(\"queststation\", \"quest_".$modulename."\");\n";
$code .= "	if (\$hookname == \"footer-runmodule\" && \$queststation == 1 && \$script == \"".$hostscript."\") {\n";
$code .= "		addnav(\"-\",\"\");\n";
$code .= "		addnav(\"".$questnavp2."\", \"runmodule.php?module=quest_".$modulename."&step=".$hostscript."1\");\n";
$code .= "	} else if (\$hookname == \"footer-runmodule\" && \$queststation == 3 && \$script == \"".$hostscript."\") {\n";
$code .= "		addnav(\"-\",\"\");\n";
$code .= "		addnav(\"".$questnavp4."\", \"runmodule.php?module=quest_".$modulename."&step=".$hostscript."2\");\n";
$code .= "	}\n";
$code .= "	return \$args;\n";
$code .= "}\n";
$code .= "\n";
$code .= "function quest_".$modulename."_runevent(\$type) {\n";
$code .= "	global \$session;\n";
$code .= "\n";
$code .= "	\$queststation = get_module_pref(\"queststation\", \"quest_".$modulename."\");\n";
$code .= "	\$questinprogress = get_module_pref(\"questinprogress\", \"questbasics\");\n";
$code .= "\n";
$code .= "	if (\$type == \"village\" && \$queststation == 0 && \$questinprogress < 1) {\n";
$code .= "		output(\"`7 ".$queststoryp1." `n`n\");\n";
$code .= "		start_quest(\"quest_".$modulename."\");\n";
$code .= "	} else if (\$type == \"forest\" && \$queststation == 2) {\n";
$code .= "		output(\"`7 ".$queststoryp3."`n`n\");\n";
$code .= "		advance_quest(\"quest_".$modulename."\");\n";
$code .= "	} else if (\$type == \"village\" && \$queststation == 4) {\n";
$code .= "		page_header(\" ".$questendheader." \");\n";
$code .= "		output(\"`7 ".$queststoryend."\");\n";
$code .= "		end_quest(\"quest_".$modulename."\");\n";
$code .= "		villagenav();\n";
$code .= "		page_footer();\n";
$code .= "	}\n";
$code .= "}\n";
$code .= "\n";
$code .= "function quest_".$modulename."_run(){\n";
$code .= "	global \$session;\n";
$code .= "	\$step = httpget('step');\n";
$code .= "\n";
$code .= "	if (\$step == \"".$hostscript."1\") {\n";
$code .= "		page_header(\" ".$questlongtitle." \");\n";
$code .= "		output(\"`7 ".$queststoryp2." `n`n\");\n";
$code .= "		advance_quest(\"quest_".$modulename."\");\n";
$code .= "		villagenav();\n";
$code .= "		page_footer();\n";
$code .= "	} else if (\$step == \"".$hostscript."2\") {\n";
$code .= "		page_header(\" ".$questlongtitle." \");\n";
$code .= "		output(\"`7 ".$queststoryp4."`n`n\");\n";
$code .= "		advance_quest(\"quest_".$modulename."\");\n";
$code .= "		villagenav();\n";
$code .= "		page_footer();\n";
$code .= "	}\n";
$code .= "}\n";
$code = str_replace("*Q*",escapeshellcmd("\""),$code);

rawoutput("<form method='post' action='runmodule.php?module=modulebuilder&op=quest' name='questbuilder'>");
rawoutput("<input type='hidden' name='modulename' value='".$modulename."'> ");
rawoutput("<input type='hidden' name='moduletitle' value='".$moduletitle."'> ");
rawoutput("<input type='hidden' name='hostscript' value='".$hostscript."'> ");
rawoutput("<input type='hidden' name='hostscriptver' value='".$hostscriptver."'> ");
rawoutput("<input type='hidden' name='hostscriptinfo' value='".$hostscriptinfo."'> ");
rawoutput("<input type='hidden' name='questlongtitle' value='".$questlongtitle."'> ");
rawoutput("<input type='hidden' name='queststep0mess' value='".$queststep0mess."'> ");
rawoutput("<input type='hidden' name='queststoryp1' value='".$queststoryp1."'> ");
rawoutput("<input type='hidden' name='queststep1mess' value='".$queststep1mess."'> ");
rawoutput("<input type='hidden' name='queststoryp2' value='".$queststoryp2."'> ");
rawoutput("<input type='hidden' name='queststep2mess' value='".$queststep2mess."'> ");
rawoutput("<input type='hidden' name='questnavp2' value='".$questnavp2."'> ");
rawoutput("<input type='hidden' name='queststoryp3' value='".$queststoryp3."'> ");
rawoutput("<input type='hidden' name='queststep3mess' value='".$queststep3mess."'> ");
rawoutput("<input type='hidden' name='queststoryp4' value='".$queststoryp4."'> ");
rawoutput("<input type='hidden' name='queststep4mess' value='".$queststep4mess."'> ");
rawoutput("<input type='hidden' name='questnavp4' value='".$questnavp4."'> ");
rawoutput("<input type='hidden' name='queststoryend' value='".$queststoryend."'> ");
rawoutput("<input type='hidden' name='questsuccessmess' value='".$questsuccessmess."'> ");
rawoutput("<input type='hidden' name='questfailmess' value='".$questfailmess."'> ");
rawoutput("<input type='hidden' name='completecode' value='".htmlspecialchars($code, ENT_QUOTES)."'> ");
rawoutput("<input type='hidden' name='modulesubmit' value=''> ");
rawoutput("<input name='Submit' value='Make Changes' type='submit'>");
rawoutput("<input name='savemodule' value='Save Module' type='submit'></form>");
addnav("","runmodule.php?module=modulebuilder&op=quest");

rawoutput("<table style='width: 100%; text-align: left;' border='0' cellpadding='2' cellspacing='2'><tbody>");
rawoutput("<tr><td style='vertical-align: top;'><pre><code>".highlight_string("<?php\n$code\n?>",true)."</code></pre><br></td></tr></tbody></table>");
}
?>