<?php
function foilwench2_getmoduleinfo(){
	$info = array(
		"name"=>"Foil Wench Part 2",
		"version"=>"1.01",
		"author"=>"DaveS, XChrisX; based on FoilWench",
		"category"=>"Forest Specials",
		"download"=>"",
		"settings"=>array(
			"Foil Wench Part 2,title",
			"forest"=>"Chance to encounter in the forest:,range,1,100,1|100",
		),
		"prefs"=>array(
			"Foil Wench Part 2,title",
			"done"=>"Has specialty been refreshed today?,bool|",
		),
	);
	return $info;
}
function foilwench2_chance() {
	$ret= get_module_setting('forest','foilwench2');
	if (get_module_pref("done",'foilwench2')==1) $ret=0;
	return $ret;
}

function foilwench2_install(){
	module_addeventhook("forest","require_once(\"modules/foilwench2.php\");
	return foilwench2_chance();");
	module_addhook("newday");
	return true;
}
function foilwench2_uninstall(){
	return true;
}
function foilwench2_dohook($hookname,$args){
	switch ($hookname) {
		case "newday":
			set_module_pref("done",0);
		break;
	}
	return $args;
}
function foilwench2_runevent($type) {
	global $session;
	$op = httpget('op');
	$from = "forest.php?";
	$session['user']['specialinc'] = "module:foilwench2";
	set_module_pref("done",1);
	if ($session['user']['specialty'] == "") {
		output("You step into a clearing and are surrounded by the most amazingly beautiful fairies you've ever seen.");
		output("Just as they're about to embrace you into their world, they notice that you have no direction in your life.");
		output("`n`nThey leave in a huff, advising you that perhaps you should go find a calling for yourself.");
		$session['user']['specialinc']="";
		return;
	}
	require_once("lib/increment_specialty.php");
	$colors = array(""=>"`7");
	$colors = modulehook("specialtycolor", $colors);
	$c = $colors[$session['user']['specialty']];
	if ($op=="give"){
		if ($session['user']['gems']>0){
			output("%sYou give `@Foil`&wench%s a gem, and she invites you to look into the bucket.`n`n", $c, $c);
			output("You look in and see a tentacle whip out and attach to your head.  You try to pull back but its too late!!`n`n");
			output("`@Foil`&wench$c laughs... \"`&Don't be such a chicken.  Enjoy the ride!$c\"`3");
			//Code by XChrisX
			global $block_new_output, $mostrecentmodule;
			$mod = $mostrecentmodule;
			$safe = $session;
			$block_new_output = true; // suppress output generated by the following modules.
			$specialties = modulehook("specialtymodules", array());
			foreach($specialties as $name => $file) {
			  require_once("modules/$file.php");
			  $mostrecentmodule = $file;
			  $fname = $file . "_dohook";
			  $fname("newday", array());
			}
			$session = $safe;
			$block_new_output = false; // re-allow output
			$mostrecenmodule = $mod;
			output("`n`nYour specialty uses have been restored.");
			//end XChrisX code
			$session['user']['gems']--;
			debuglog("gave 1 gem to Foilwench and gained a specialty revitalization.");
		}else{
			output("%sYou hand over your imaginary gem.", $c);
			output("`@Foil`&wench%s stares blankly back at you and drops the bucket back into the well before you get a chance to peer over the side.", $c);
			output("\"`&Come back when you have a `breal`b gem you flim-flam.%s\"`n`n", $c);
			output("\"`#Flim-Flam?%s\" you ask.`n`n", $c);
			output("With that, `@Foil`&wench%s turns her back on you and you leave.`0", $c);
		}
		$session['user']['specialinc']="";
	}elseif($op=="dont"){
		output("%sYou notice a strange tentacle coming over the edge of the bucket and decide that perhaps you should look elsewhere for your 'super mystical inspiration'.", $c);
		$session['user']['specialinc']="";
	}elseif($session['user']['specialty']!=""){
		output("%sYou are seeking prey in the forest when you wander by an opening.  There's an old woman standing by a well cranking up a bucket.", $c);
		output("Assuming she's bringing up water, you approach her just as the bucket is about to come over the edge.");
		output("\"`&Ha ha! I've been waiting for you, %s`&, for I am `@Foil`&wench.%s\"`n`n", $session['user']['name'], $c);
		output("\"`#Hey... how did you know my name??%s\" you inquire.`n`n", $c);
		output("\"`&Oh come on.  It's right on your name tag.  Don't act all surprised.  I'm not some super mystic or anything.%s\"`n`n", $c);
		output("\"`#Oh, yeah%s\" you stumble out.  You look down and notice the name tag from your last `0'I'm good enough, I'm smart enough'%s convention that you went to and you tear it off.`n`n", $c,$c);
		output("The old woman ignores your actions. \"`&Here's the deal.  I'll show you what's in the bucket, but I have two conditions.%s\"`n`n", $c);
		output("\"`#Two conditions?%s\" you repeat inquisitively.`n`n", $c);
		output("\"`&Yes.  First, you must give me a gem, and second you must go away afterwards!%s\"`n`n", $c);
		output("\"`#Hmmmm... What will happen?%s\" you ask.`n`n", $c);
		output("\"`&Well, to be honest with you, I kind of did lie.  I AM a bit of a super mystic.  So it will have to be a surprise.%s\"", $c);
		addnav("Give her a gem", $from."op=give");
		addnav("Don't give her a gem",$from."op=dont");
	}
}
function foilwench2_run(){
}
?>
