<?php

function prankstore_getmoduleinfo(){
	$info = array(
		"name"=>"Prankatorium",
		"version"=>"5.04",
		"author"=>"DaveS, idea by Stinei",
		"category"=>"Village",
		"download"=>"http://dragonprime.net/index.php?module=Downloads;sa=dlview;id=1076",
		"description"=>"Pull Pranks on other Players",
		"settings"=>array(
            "Prankatorium,title",
            "storename"=>"What is the name of the Prankatorium?,text|Kacz's Prankatorium",
            "owner"=>"Who is the owner of the store?,text|Kacz",
            "sex"=>"What is the sex of the owner?,enum,0,Male,1,Female|0",
			"storeloc"=>"Where does the Prankatorium appear?,location|".getsetting("villagename", LOCATION_FIELDS),
			"chanceopen"=>"What percent chance is there for the shop to appear in the village?,range,1,100,1|30",
			"dks"=>"Minimum number of dks to enter the Prankatorium?,int|0",
			"limit"=>"Limit number of pranks pulled by a player to once per dk?,bool|0",
			"hof"=>"Allow Hall of Fame for most pranks pulled?,bool|1",
			"YOM Pranks,title",
			"Leave blank to disable,note",
			"percent1"=>"System YoM 1: What percent chance will this occur each newday?,range,0,100,1|80",
			"result1"=>"System YoM 1: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank1"=>"System YoM 1: A. What is player compared to?,text|a Boneless Chicken",
			"2prank1"=>"System YoM 1: B. What is player compared to?,text|a Slug on a Salt Lick",
			"3prank1"=>"System YoM 1: C. What is player compared to?,text|a sloth taking sleeping pills",
			"cost1"=>"System YoM 1: How much does this prank cost?,int|3000",
			"prankon1"=>"System YoM 1: Who is this prank being pulled on today?,int|0",
			"percent2"=>"System YoM 2: What percent chance will this occur each newday?,range,0,100,1|30",
			"result2"=>"System YoM 2: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank2"=>"System YoM 2: A. What is player's mother is so old that?,text|she gave a dinosaur pneumonia",
			"2prank2"=>"System YoM 2: B. What is player's mother is so old that?,text|she owes Socrates a penny",
			"3prank2"=>"System YoM 2: C. What is player's mother is so old that?,text|her flatulence is made of dust",
			"cost2"=>"System YoM 2: How much does this prank cost?,int|4000",
			"prankon2"=>"System YoM 2: Who is this prank being pulled on today?,int|0",
			"percent3"=>"System YoM 3: What percent chance will this occur each newday?,range,0,100,1|5",
			"result3"=>"System YoM 3: Which prank is available today?,enum,0,None,1,A,2,B,3,C|0",
			"1prank3"=>"System YoM 3: A. What is player dumber than?,text|a zombie using cheese as a brain",
			"2prank3"=>"System YoM 3: B. What is player dumber than?,text|a box of very poor quality rocks",
			"3prank3"=>"System YoM 3: C. What is player dumber than?,text|a chicken that got lost crossing the road",
			"cost3"=>"System YoM 3: How much does this prank cost?,int|5000",
			"prankon3"=>"System YoM 3: Who is this prank being pulled on today?,int|0",
			"News Pranks,title",
			"percent4"=>"News 1: What percent chance will this occur each newday?,range,0,100,1|95",
			"result4"=>"News 1: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank4"=>"News 1: A. Report that player has the following disease:,text|a nasty case of infectious lip herpes",
			"2prank4"=>"News 1: B. Report that player has the following disease:,text|a wart so large it looks like a 2nd nose",
			"3prank4"=>"News 1: C. Report that player has the following disease:,text|pimples growing hairs",
			"cost4"=>"News 1: How much does this prank cost?,int|15",
			"prankon4"=>"News 1: Who is this prank being pulled on today?,int|0",
			"percent5"=>"News 2: What percent chance will this occur each newday?,range,0,100,1|60",
			"result5"=>"News 2: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank5"=>"News 2: A. Report that player was seen doing the following:,text|eating old mustard in a dumpster",
			"2prank5"=>"News 2: B. Report that player was seen doing the following:,text|losing a game of checkers with a drunken monkey",
			"3prank5"=>"News 2: C. Report that player was seen doing the following:,text|licking peanut butter off a donkey's butt",
			"cost5"=>"News 2: How much does this prank cost?,int|35",
			"prankon5"=>"News 2: Who is this prank being pulled on today?,int|0",
			"percent6"=>"News 3: What percent chance will this occur each newday?,range,0,100,1|20",
			"result6"=>"News 3: Which prank is available today?,enum,0,None,1,A,2,B,3,C|0",
			"1prank6"=>"News 3: A. Report that player was seen,text|making love to a fire hydrant while sleep walking",
			"2prank6"=>"News 3: B. Report that player was seen,text|catching duck droppings on their tongue",
			"3prank6"=>"News 3: C. Report that player was seen,text|sucking on the bottom of the fountain looking for gold pieces",
			"cost6"=>"News 3: How much does this prank cost?,int|55",
			"prankon6"=>"News 3: Who is this prank being pulled on today?,int|0",
			"Scrolling Pranks,title",
			"percent7"=>"Scroll 1: What percent chance will this occur each newday?,range,0,100,1|90",
			"result7"=>"Scroll 1: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank7"=>"Scroll 1: A. Scroll that the player has the following health problem:,text|such bad body odor that skunks can't stand the smell",
			"2prank7"=>"Scroll 1: B. Scroll that the player has the following health problem:,text|such poor bowel control that the farts are killing kittens",
			"3prank7"=>"Scroll 1: C. Scroll that the player has the following health problem:,text|such bad breath that it's killing all the flowers",
			"cost7"=>"Scroll 1: How much does this prank cost?,int|1500",
			"prankon7"=>"Scroll 1: Who is this prank being pulled on today?,int|0",
			"percent8"=>"Scroll 2: What percent chance will this occur each newday?,range,0,100,1|20",
			"result8"=>"Scroll 2: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank8"=>"Scroll 2: A. Scroll that the player was seen:,text|reading a manual on how to seduce sheep",
			"2prank8"=>"Scroll 2: B. Scroll that the player was seen:,text|sleeping in a homeless person's armpit",
			"3prank8"=>"Scroll 2: C. Scroll that the player was seen:,text|killing butterflies by snorting them",
			"cost8"=>"Scroll 2: How much does this prank cost?,int|2000",
			"prankon8"=>"Scroll 2: Who is this prank being pulled on today?,int|0",
			"percent9"=>"Scroll 3: What percent chance will this occur each newday?,range,0,100,1|8",
			"result9"=>"Scroll 3: Which prank is available today?,enum,0,None,1,A,2,B,3,C|0",
			"1prank9"=>"Scroll 3: A. Scroll that the player has:,text|just finished eating a bowl of head lice",
			"2prank9"=>"Scroll 3: B. Scroll that the player has:,text|flossed three teeth using a rat tail",
			"3prank9"=>"Scroll 3: C. Scroll that the player has:,text|been known to eat scabs from the back of a camel",
			"cost9"=>"Scroll 3: How much does this prank cost?,int|2500",
			"prankon9"=>"Scroll 3: Who is this prank being pulled on today?,int|0",
			"Weapon Pranks,title",
			"percent10"=>"Weapon 1: What percent chance will this occur each newday?,range,0,100,1|90",
			"result10"=>"Weapon 1: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank10"=>"Weapon 1: A. Prank Weapon 1:,text|Wet Noodle",
			"2prank10"=>"Weapon 1: B. Prank Weapon 1:,text|Rubber Chicken",
			"3prank10"=>"Weapon 1: C. Prank Weapon 1:,text|Balloon in the shape of a Poodle",
			"cost10"=>"Weapon 1: How much does this prank cost?,int|200",
			"prankon10"=>"Weapon 1: Who is this prank being pulled on today?,int|0",
			"weapon10"=>"Weapon 1: What is the player's old weapon?,text|",
			"percent11"=>"Weapon 2: What percent chance will this occur each newday?,range,0,100,1|30",
			"result11"=>"Weapon 2: Which prank is available today?,enum,0,None,1,A,2,B,3,C|0",
			"1prank11"=>"Weapon 2: A. Prank Weapon 2:,text|Very Flimsy Plastic Butter Knife",
			"2prank11"=>"Weapon 2: B. Prank Weapon 2:,text|Belly Button Lint",
			"3prank11"=>"Weapon 2: C. Prank Weapon 2:,text|Extra Long Nose Hair",
			"cost11"=>"Weapon 2: System YoM 1: How much does this prank cost?,int|250",
			"prankon11"=>"Weapon 2: Who is this prank being pulled on today?,int|0",
			"weapon11"=>"Weapon 2: What is the player's old weapon?,text|",
			"percent12"=>"Weapon 3: What percent chance will this occur each newday?,range,0,100,1|15",
			"result12"=>"Weapon 3: Which prank is available today?,enum,0,None,1,A,2,B,3,C|0",
			"1prank12"=>"Weapon 3: A. Prank Weapon 3:,text|Spit Ball Hurled at High Velocity",
			"2prank12"=>"Weapon 3: B. Prank Weapon 3:,text|Pimple Pus Grenades",
			"3prank12"=>"Weapon 3: C. Prank Weapon 3:,text|Soggy Cow Chips",
			"cost12"=>"Weapon 3: How much does this prank cost?,int|300",
			"prankon12"=>"Weapon 3: Who is this prank being pulled on today?,int|0",
			"weapon12"=>"Weapon 3: What is the player's old weapon?,text|",
			"Vital Info Pranks,title",
			"percent13"=>"Vital Info 1: What percent chance will this occur each newday?,range,0,100,1|95",
			"result13"=>"Vital Info 1: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank13"=>"Vital Info 1: A. Fake info on Bowel Movements:,text|Explosive Diarrhea",
			"2prank13"=>"Vital Info 1: B. Fake info on Bowel Movements:,text|Highly Constipated",
			"3prank13"=>"Vital Info 1: C. Fake info on Bowel Movements:,text|Leaky Discharge",
			"cost13"=>"Vital Info 1: How much does this prank cost?,int|500",
			"prankon13"=>"Vital Info 1: Who is this prank being pulled on today?,int|0",
			"percent14"=>"Vital Info 2: What percent chance will this occur each newday?,range,0,100,1|25",
			"result14"=>"Vital Info 2: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank14"=>"Vital Info 2: A. Fake info on Back Hair:,text|In French Braids",
			"2prank14"=>"Vital Info 2: B. Fake info on Back Hair:,text|Rainbow Colored Dye Job",
			"3prank14"=>"Vital Info 2: C. Fake info on Back Hair:,text|Mullet Style",
			"cost14"=>"Vital Info 2: How much does this prank cost?,int|650",
			"prankon14"=>"Vital Info 2: Who is this prank being pulled on today?,int|0",
			"percent15"=>"Vital Info 3: What percent chance will this occur each newday?,range,0,100,1|20",
			"result15"=>"Vital Info 3: Which prank is available today?,enum,0,None,1,A,2,B,3,C|0",
			"1prank15"=>"Vital Info 3: A. Fake info on Potency:,text|Flaccid",
			"2prank15"=>"Vital Info 3: B. Fake info on Potency:,text|Extremely Lacking",
			"3prank15"=>"Vital Info 3: C. Fake info on Potency:,text|Insomnia Inducing",
			"cost15"=>"Vital Info 3: How much does this prank cost?,int|800",
			"prankon15"=>"Vital Info 3: Who is this prank being pulled on today?,int|0",
			"Title Change Pranks,title",
			"percent16"=>"Title 1: What percent chance will this occur each newday?,range,0,100,1|85",
			"result16"=>"Title 1: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank16"=>"Title 1: A. Fake Title:,text|FoulOdor",
			"2prank16"=>"Title 1: B. Fake Title:,text|FrogBreath",
			"3prank16"=>"Title 1: C. Fake Title:,text|Flatulent",
			"cost16"=>"Title 1: How much does this prank cost?,int|800",
			"prankon16"=>"Title 1: Who is this prank being pulled on today?,int|",
			"title16"=>"Title 1: What is the player's old title?,text|",
			"percent17"=>"Title 2: What percent chance will this occur each newday?,range,0,100,1|35",
			"result17"=>"Title 2: Which prank is available today?,enum,0,None,1,A,2,B,3,C|1",
			"1prank17"=>"Title 2: A. Fake Title:,text|RatFace",
			"2prank17"=>"Title 2: B. Fake Title:,text|HairlessCat",
			"3prank17"=>"Title 2: C. Fake Title:,text|DogSniffer",
			"cost17"=>"Title 2: How much does this prank cost?,int|1250",
			"prankon17"=>"Title 2: Who is this prank being pulled on today?,int|",
			"title17"=>"Title 2: What is the player's old title?,text|",
			"percent18"=>"Title 3: What percent chance will this occur each newday?,range,0,100,1|18",
			"result18"=>"Title 3: Which prank is available today?,enum,0,None,1,A,2,B,3,C|0",
			"1prank18"=>"Title 3: A. Fake Title:,text|LimpWristed",
			"2prank18"=>"Title 3: B. Fake Title:,text|Weakling",
			"3prank18"=>"Title 3: C. Fake Title:,text|Insignificant",
			"cost18"=>"Title 3: How much does this prank cost?,int|1400",
			"prankon18"=>"Title 3: Who is this prank being pulled on today?,int|",
			"title18"=>"Title 3: What is the player's old title?,text|",
		),
        "prefs"=>array(
			"Prankatorium,title",
			"user_prank"=>"Block from Receiving a YoM when a mail Prank is pulled?,bool|0",
			"totalpranks"=>"How many pranks has this player pulled?,int|0",
			"pranker"=>"What number prank has the player played today?,range,0,20,1|",
		),
	);
	return $info;
}
function prankstore_install(){
	module_addhook("changesetting");
	module_addhook("village");
	module_addhook("footer-hof");
	module_addhook("newday-runonce");
	module_addhook("dragonkill");
	module_addhook("charstats");
	return true;
}
function prankstore_uninstall(){
	return true;
}
function prankstore_dohook($hookname,$args){
	global $session;
	require("modules/prankstore/dohook/$hookname.php");
	return $args;
}
function prankstore_run(){
	include("modules/prankstore/prankstore.php");
}
?>