<?php
if ($modulename == "" or $modulesubmit == ""){
			rawoutput("<form method='post' action='runmodule.php?module=modulebuilder&op=specialty' name='specialty'>");
			rawoutput("<span style='font-weight: bold; text-decoration: underline;'>Basics</span><br>");
			rawoutput("Module Name: <input value = '".$modulename."' size='25' name='modulename'><br>");
			rawoutput("Module Title: <input value = '".$moduletitle."' size='40' name='moduletitle'><br>");
			rawoutput("Module Description:<br>&nbsp;<input value = '".$moduledesc."' size='60' name='moduledesc'><br><br>");
			rawoutput("<span style='font-weight: bold; text-decoration: underline;'>Mechanics</span><br>");
			rawoutput("Specialty Code: <input value = '".$specialtycode."' size='5' name='specialtycode'><br>");
			rawoutput("Specialty Youth Memory:<br>&nbsp;<textarea cols='40' rows='4' name='specmemories'>".$specmemories."</textarea><br>");
			rawoutput("Specialty Picked Message:<br>&nbsp;<input value = '".$specstory."' size='60' name='specstory'><br><br>");
			rawoutput("<span style='font-weight: bold; text-decoration: underline;'>Skills - Leave unused values blank</span><br>");
			//1st skill
			rawoutput("<span style='font-weight: bold;'>1st Skill</span><br>");
			rawoutput("Start Message:<br><input value = '".$startmsg1."' size='60' name='startmsg1'><br>");
			rawoutput("Skill Name: <input value = '".$skill1."' size='25' name='skill1'><br>");
			rawoutput("Rounds to Last: <input value = '".$skill1rounds."' size='4' name='skill1rounds'><br>");
			rawoutput("Wearoff Message:<br><input value = '".$skill1wearoff."' size='60' name='skill1wearoff'><br>");
			rawoutput("Damage Shield: <input value = '".$skill1dmgshield."' size='4' name='skill1dmgshield'><br>");
			rawoutput("Life Tap: <input value = '".$skill1lifetap."' size='4' name='skill1lifetap'><br>");
			rawoutput("Regeneration (+ user level): <input value = '".$skill1regen."' size='4' name='skill1regen'><br>");
			rawoutput("Player Attack Mod: <input value = '".$skill1atkmod."' size='3' name='skill1atkmod'><br>");
			rawoutput("Player Defence Mod: <input value = '".$skill1defmod."' size='3' name='skill1defmod'><br>");
			rawoutput("Opponent Defence Mod: <input value = '".$skill1bguydefmod."' size='3' name='skill1badguydefmod'><br>");
			rawoutput("Effect Message: <br> <input value = '".$skill1effmsg."' size='60' name='skill1effmsg'><br>");
			rawoutput("Effect No Damage Message: <br> <input value = '".$skill1nodmg."' size='60' name='skill1nodmg'><br>");
			rawoutput("Effect Effect Fail Message: <br> <input value = '".$skill1efffail."' size='60' name='skill1efffail'><br>");
			rawoutput("Minion Count: <input value = '".$skill1minion."' size='3' name='skill1minion'><br>");
			rawoutput("Max Opponent Damage: <input value = '".$skill1maxbguydam."' size='4' name='skill1maxbguydam'><br><br>");
			//2nd skill
			rawoutput("<span style='font-weight: bold;'>2nd Skill</span><br>");
			rawoutput("Start Message:<br><input value = '".$startmsg2."' size='60' name='startmsg2'><br>");
			rawoutput("Skill Name: <input value = '".$skill2."' size='25' name='skill2'><br>");
			rawoutput("Rounds to Last: <input value = '".$skill2rounds."' size='4' name='skill2rounds'><br>");
			rawoutput("Wearoff Message:<br><input value = '".$skill2wearoff."' size='60' name='skill2wearoff'><br>");
			rawoutput("Damage Shield: <input value = '".$skill2dmgshield."' size='4' name='skill2dmgshield'><br>");
			rawoutput("Life Tap: <input value = '".$skill2lifetap."' size='4' name='skill2lifetap'><br>");
			rawoutput("Regeneration (+ user level): <input value = '".$skill2regen."' size='4' name='skill2regen'><br>");
			rawoutput("Player Attack Mod: <input value = '".$skill2atkmod."' size='3' name='skill2atkmod'><br>");
			rawoutput("Player Defence Mod: <input value = '".$skill2defmod."' size='3' name='skill2defmod'><br>");
			rawoutput("Opponent Defence Mod: <input value = '".$skill2bguydefmod."' size='3' name='skill2badguydefmod'><br>");
			rawoutput("Effect Message: <br> <input value = '".$skill2effmsg."' size='60' name='skill2effmsg'><br>");
			rawoutput("Effect No Damage Message: <br> <input value = '".$skill2nodmg."' size='60' name='skill2nodmg'><br>");
			rawoutput("Effect Effect Fail Message: <br> <input value = '".$skill2efffail."' size='60' name='skill2efffail'><br>");
			rawoutput("Minion Count: <input value = '".$skill2minion."' size='3' name='skill2minion'><br>");
			rawoutput("Max Opponent Damage: <input value = '".$skill2maxbguydam."' size='4' name='skill2maxbguydam'><br><br>");
			//3rd skill
			rawoutput("<span style='font-weight: bold;'>3rd Skill</span><br>");
			rawoutput("Start Message:<br><input value = '".$startmsg3."' size='60' name='startmsg3'><br>");
			rawoutput("Skill Name: <input value = '".$skill3."' size='25' name='skill3'><br>");
			rawoutput("Rounds to Last: <input value = '".$skill3rounds."' size='4' name='skill3rounds'><br>");
			rawoutput("Wearoff Message:<br><input value = '".$skill3wearoff."' size='60' name='skill3wearoff'><br>");
			rawoutput("Damage Shield: <input value = '".$skill3dmgshield."' size='4' name='skill3dmgshield'><br>");
			rawoutput("Life Tap: <input value = '".$skill3lifetap."' size='4' name='skill3lifetap'><br>");
			rawoutput("Regeneration (+ user level): <input value = '".$skill3regen."' size='4' name='skill3regen'><br>");
			rawoutput("Player Attack Mod: <input value = '".$skill3atkmod."' size='3' name='skill3atkmod'><br>");
			rawoutput("Player Defence Mod: <input value = '".$skill3defmod."' size='3' name='skill3defmod'><br>");
			rawoutput("Opponent Defence Mod: <input value = '".$skill3bguydefmod."' size='3' name='skill3badguydefmod'><br>");
			rawoutput("Effect Message: <br> <input value = '".$skill3effmsg."' size='60' name='skill3effmsg'><br>");
			rawoutput("Effect No Damage Message: <br> <input value = '".$skill3nodmg."' size='60' name='skill3nodmg'><br>");
			rawoutput("Effect Effect Fail Message: <br> <input value = '".$skill3efffail."' size='60' name='skill3efffail'><br>");
			rawoutput("Minion Count: <input value = '".$skill3minion."' size='3' name='skill3minion'><br>");
			rawoutput("Max Opponent Damage: <input value = '".$skill3maxbguydam."' size='4' name='skill3maxbguydam'><br><br>");
			//4th skill
			rawoutput("<span style='font-weight: bold;'>4th Skill</span><br>");
			rawoutput("Start Message:<br><input value = '".$startmsg5."' size='60' name='startmsg5'><br>");
			rawoutput("Skill Name: <input value = '".$skill5."' size='25' name='skill5'><br>");
			rawoutput("Rounds to Last: <input value = '".$skill5rounds."' size='4' name='skill5rounds'><br>");
			rawoutput("Wearoff Message:<br><input value = '".$skill5wearoff."' size='60' name='skill5wearoff'><br>");
			rawoutput("Damage Shield: <input value = '".$skill5dmgshield."' size='4' name='skill5dmgshield'><br>");
			rawoutput("Life Tap: <input value = '".$skill5lifetap."' size='4' name='skill5lifetap'><br>");
			rawoutput("Regeneration (+ user level): <input value = '".$skill5regen."' size='4' name='skill5regen'><br>");
			rawoutput("Player Attack Mod: <input value = '".$skill5atkmod."' size='3' name='skill5atkmod'><br>");
			rawoutput("Player Defence Mod: <input value = '".$skill5defmod."' size='3' name='skill5defmod'><br>");
			rawoutput("Opponent Defence Mod: <input value = '".$skill5bguydefmod."' size='3' name='skill5badguydefmod'><br>");
			rawoutput("Effect Message: <br> <input value = '".$skill5effmsg."' size='60' name='skill5effmsg'><br>");
			rawoutput("Effect No Damage Message: <br> <input value = '".$skill5nodmg."' size='60' name='skill5nodmg'><br>");
			rawoutput("Effect Effect Fail Message: <br> <input value = '".$skill5efffail."' size='60' name='skill5efffail'><br>");
			rawoutput("Minion Count: <input value = '".$skill5minion."' size='3' name='skill5minion'><br>");
			rawoutput("Max Opponent Damage: <input value = '".$skill5maxbguydam."' size='4' name='skill5maxbguydam'><br><br>");
			rawoutput("<span style='font-weight: bold; text-decoration: underline;'>Castle Library</span><br>");
			rawoutput("Name of Book: <input value = '".$bookname."' size='25' name='bookname'><br>");
			rawoutput("Book Message: <input value = '".$bookmessage."' size='60' name='bookmessage'><br><br>");
			rawoutput("<input type='hidden' name='modulesubmit' value='done'> ");
			rawoutput("<input name='Submit' value='Submit' type='submit'><br></form>");
			addnav("","runmodule.php?module=modulebuilder&op=specialty");
		}else{
			$code1 = "function specialty_".$modulename."_getmoduleinfo(){\n";
			$code1 .= "	\$info = array(\n";
			$code1 .= "		\"name\" => \"Specialty - ".$moduletitle."\",\n";
			$code1 .= "		\"author\" => \"".get_module_pref("author")." - Built with Module Builder by `3Lonny Luberts`0\",\n";
			$code1 .= "		\"version\" => \"1.0\",\n";
			$code1 .= "		\"download\" => \"".get_module_pref("downloc")."specialty_".$modulename.".zip\",\n";
			$code1 .= "		\"description\"=>\"".$moduledesc."\",\n";
			$code1 .= "		\"vertxtloc\"=>\"".get_module_pref("vertxtloc")."\",\n";
			$code1 .= "		\"category\" => \"Specialties\",\n";
			$code1 .= "		\"settings\"=> array(\n";
			$code1 .= "			\"Specialty - ".$moduletitle." Settings,title\",\n";
			$code1 .= "			\"mindk\"=>\"How many DKs do you need before the specialty is available?,int|10\",\n";
			$code1 .= "			\"cost\"=>\"How many points do you need before the specialty is available?,int|0\",\n";
			$code1 .= "		),\n";
			$code1 .= "		\"prefs\" => array(\n";
			$code1 .= "			\"Specialty - ".$moduletitle." Skills User Prefs,title\",\n";
			$code1 .= "			\"skill\"=>\"Skill points in ".$moduletitle." Skills,int|0\",\n";
			$code1 .= "			\"uses\"=>\"Uses of ".$moduletitle." Skills allowed,int|0\",\n";
			$code1 .= "		),\n";
			$code1 .= "	);\n";
			$code1 .= "	return \$info;\n";
			$code1 .= "}\n";
			$code1 .= "\n";
			$code1 .= "function specialty_".$modulename."_install(){\n";
			$code1 .= "	\$specialty=\"".$specialtycode."\";\n";
			$code1 .= "	module_addhook(\"apply-specialties\");\n";
			$code1 .= "	module_addhook(\"castlelib\");\n";
			$code1 .= "	module_addhook(\"castlelibbook\");\n";
			$code1 .= "	module_addhook(\"choose-specialty\");\n";
			$code1 .= "	module_addhook(\"dragonkill\");\n";
			$code1 .= "	module_addhook(\"fightnav-specialties\");\n";
			$code1 .= "	module_addhook(\"incrementspecialty\");\n";
			$code1 .= "	module_addhook(\"newday\");\n";
			$code1 .= "	module_addhook(\"pointsdesc\");\n";
			$code1 .= "	module_addhook(\"set-specialty\");\n";
			$code1 .= "	module_addhook(\"specialtycolor\");\n";
			$code1 .= "	module_addhook(\"specialtymodules\");\n";
			$code1 .= "	module_addhook(\"specialtynames\");\n";
			$code1 .= "	return true;\n";
			$code1 .= "}\n";
			$code1 .= "\n";
			$code1 .= "function specialty_".$modulename."_uninstall(){\n";
			$code1 .= "	\$sql = \"UPDATE \" . db_prefix(\"accounts\") . \" SET specialty='' WHERE specialty='".$specialtycode."'\";\n";
			$code1 .= "	db_query(\$sql);\n";
			$code1 .= "	return true;\n";
			$code1 .= "}\n";
			$code1 .= "\n";
			$code1 .= "function specialty_".$modulename."_dohook(\$hookname,\$args){\n";
			$code1 .= "	global \$session,\$resline;\n";
			$code1 .= "	tlschema(\"fightnav\");\n";
			$code1 .= "\n";
			$code1 .= "	\$spec = \"".$specialtycode."\";\n";
			$code1 .= "	\$name = \"".$moduletitle."\";\n";
			$code1 .= "	\$ccode = \"`7\";\n";
			$code1 .= "	\$cost = get_module_setting(\"cost\");\n";
			$code1 .= "	\$op69 = httpget('op69');\n";
			$code1 .= "\n";
			$code1 .= "	switch (\$hookname) {\n";
			$code1 .= "\n";
			$code1 .= "	case \"apply-specialties\":\n";
			$code1 .= "		\$skill = httpget('skill');\n";
			$code1 .= "		\$l = httpget('l');\n";
			$code1 .= "		if (\$skill==\$spec){\n";
			$code1 .= "			if (get_module_pref(\"uses\") >= \$l){\n";
			$code1 .= "				switch(\$l){\n";
			$code1 .= "				case 1:\n";
			//add conditionals so it only builds good values
			$code1 .= "				apply_buff('".$specialtycode."1', array(\n";
			$code1 .= "				\"startmsg\"=>\"".$startmsg1."\",\n";
			$code1 .= "				\"name\"=>\"".$skill1."\",\n";
			$code1 .= "				\"rounds\"=>\"".$skill1rounds."\",\n";
			if ($skill1wearoff <> "") $code1 .= "	\"wearoff\"=>\"".$skill1wearoff."\",\n";
			if ($skill1dmgshield <> "") $code1 .= "	\"damageshield\"=>\"".$skill1dmgshield."\",\n";
			if ($skill1lifetap <> "") $code1 .= "	\"lifetap\"=>\"".$skill1lifetap."\",\n";
			if ($skill1regen <> "") $code1 .= "	\"regen\"=>\$session['user']['level']+".$skill1regen.",\n";
			if ($skill1atkmod <> "") $code1 .= "	\"atkmod\"=>\"".$skill1atkmod."\",\n";
			if ($skill1defmod <> "") $code1 .= "	\"defmod\"=>\"".$skill1defmod."\",\n";
			if ($skill1badguydefmod <> "") $code1 .= "\"badguydefmod\"=>\"".$skill1badguydefmod."\",\n";
			if ($skill1effmsg <> "") $code1 .= "	\"effectmsg\"=>\"".$skill1effmsg."\",\n";
			if ($skill1nodmg <> "") $code1 .= "	\"effectnodmg\"=>\"".$skill1nodmg."\",\n";
			if ($skill1efffail <> "") $code1 .= "	\"effectfailmsg\"=>\"".$skill1efffail."\",\n";
			if ($skill1minion <> "") $code1 .= "	\"minioncount\"=>round(\$session['user']['level']/2)+".$skill1minion.",\n";
			if ($skill1maxbguydam <> "") $code1 .= "\"maxbadguydamage\"=>round(\$session['user']['level']/2,0)+".$skill1maxbguydam.",\n";
			$code1 .= "				\"schema\"=>\"specialty_".$modulename."\"\n";
			$code1 .= "				));\n";
			$code1 .= "				break;\n";
			$code1 .= "				case 2:\n";
			$code1 .= "				apply_buff('".$specialtycode."2', array(\n";
			$code1 .= "				\"startmsg\"=>\"".$startmsg2."\",\n";
			$code1 .= "				\"name\"=>\"".$skill2."\",\n";
			$code1 .= "				\"rounds\"=>\"".$skill2rounds."\",\n";
			if ($skill2wearoff <> "") $code1 .= "	\"wearoff\"=>\"".$skill2wearoff."\",\n";
			if ($skill2dmgshield <> "") $code1 .= "	\"damageshield\"=>\"".$skill2dmgshield."\",\n";
			if ($skill2lifetap <> "") $code1 .= "	\"lifetap\"=>\"".$skill2lifetap."\",\n";
			if ($skill2regen <> "") $code1 .= "	\"regen\"=>\$session['user']['level']+".$skill2regen.",\n";
			if ($skill2atkmod <> "") $code1 .= "	\"atkmod\"=>\"".$skill2atkmod."\",\n";
			if ($skill2defmod <> "") $code1 .= "	\"defmod\"=>\"".$skill2defmod."\",\n";
			if ($skill2badguydefmod <> "") $code1 .= "\"badguydefmod\"=>\"".$skill2badguydefmod."\",\n";
			if ($skill2effmsg <> "") $code1 .= "	\"effectmsg\"=>\"".$skill2effmsg."\",\n";
			if ($skill2nodmg <> "") $code1 .= "	\"effectnodmg\"=>\"".$skill2nodmg."\",\n";
			if ($skill2efffail <> "") $code1 .= "	\"effectfailmsg\"=>\"".$skill2efffail."\",\n";
			if ($skill2minion <> "") $code1 .= "	\"minioncount\"=>round(\$session['user']['level']/2)+".$skill2minion.",\n";
			if ($skill2maxbguydam <> "") $code1 .= "\"maxbadguydamage\"=>round(\$session['user']['level']/2,0)+".$skill2maxbguydam.",\n";
			$code1 .= "				\"schema\"=>\"specialty_".$modulename."\"\n";
			$code1 .= "				));\n";
			$code1 .= "				break;\n";
			$code1 .= "				case 3:\n";
			$code1 .= "				apply_buff('".$specialtycode."3', array(\n";
			$code1 .= "				\"startmsg\"=>\"".$startmsg3."\",\n";
			$code1 .= "				\"name\"=>\"".$skill3."\",\n";
			$code1 .= "				\"rounds\"=>\"".$skill3rounds."\",\n";
			if ($skill3wearoff <> "") $code1 .= "	\"wearoff\"=>\"".$skill3wearoff."\",\n";
			if ($skill3dmgshield <> "") $code1 .= "	\"damageshield\"=>\"".$skill3dmgshield."\",\n";
			if ($skill3lifetap <> "") $code1 .= "	\"lifetap\"=>\"".$skill3lifetap."\",\n";
			if ($skill3regen <> "") $code1 .= "	\"regen\"=>\$session['user']['level']+".$skill3regen.",\n";
			if ($skill3atkmod <> "") $code1 .= "	\"atkmod\"=>\"".$skill3atkmod."\",\n";
			if ($skill3defmod <> "") $code1 .= "	\"defmod\"=>\"".$skill3defmod."\",\n";
			if ($skill3badguydefmod <> "") $code1 .= "\"badguydefmod\"=>\"".$skill3badguydefmod."\",\n";
			if ($skill3effmsg <> "") $code1 .= "	\"effectmsg\"=>\"".$skill3effmsg."\",\n";
			if ($skill3nodmg <> "") $code1 .= "	\"effectnodmg\"=>\"".$skill3nodmg."\",\n";
			if ($skill3efffail <> "") $code1 .= "	\"effectfailmsg\"=>\"".$skill3efffail."\",\n";
			if ($skill3minion <> "") $code1 .= "	\"minioncount\"=>round(\$session['user']['level']/2)+".$skill3minion.",\n";
			if ($skill3maxbguydam <> "") $code1 .= "\"maxbadguydamage\"=>round(\$session['user']['level']/2,0)+".$skill3maxbguydam.",\n";
			$code1 .= "				\"schema\"=>\"specialty_".$modulename."\"\n";
			$code1 .= "				));\n";
			$code1 .= "				break;\n";
			$code1 .= "				case 5:\n";
			$code1 .= "				apply_buff('".$specialtycode."5', array(\n";
			$code1 .= "				\"startmsg\"=>\"".$startmsg5."\",\n";
			$code1 .= "				\"name\"=>\"".$skill5."\",\n";
			$code1 .= "				\"rounds\"=>\"".$skill5rounds."\",\n";
			if ($skill5wearoff <> "") $code1 .= "	\"wearoff\"=>\"".$skill5wearoff."\",\n";
			if ($skill5dmgshield <> "") $code1 .= "	\"damageshield\"=>\"".$skill5dmgshield."\",\n";
			if ($skill5lifetap <> "") $code1 .= "	\"lifetap\"=>\"".$skill5lifetap."\",\n";
			if ($skill5regen <> "") $code1 .= "	\"regen\"=>\$session['user']['level']+".$skill5regen.",\n";
			if ($skill5atkmod <> "") $code1 .= "	\"atkmod\"=>\"".$skill5atkmod."\",\n";
			if ($skill5defmod <> "") $code1 .= "	\"defmod\"=>\"".$skill5defmod."\",\n";
			if ($skill5badguydefmod <> "") $code1 .= "\"badguydefmod\"=>\"".$skill5badguydefmod."\",\n";
			if ($skill5effmsg <> "") $code1 .= "	\"effectmsg\"=>\"".$skill5effmsg."\",\n";
			if ($skill5nodmg <> "") $code1 .= "	\"effectnodmg\"=>\"".$skill5nodmg."\",\n";
			if ($skill5efffail <> "") $code1 .= "	\"effectfailmsg\"=>\"".$skill5efffail."\",\n";
			if ($skill5minion <> "") $code1 .= "	\"minioncount\"=>round(\$session['user']['level']/2)+".$skill5minion.",\n";
			if ($skill5maxbguydam <> "") $code1 .= "\"maxbadguydamage\"=>round(\$session['user']['level']/2,0)+".$skill5maxbguydam.",\n";
			$code1 .= "				\"schema\"=>\"specialty_".$modulename."\"\n";
			$code1 .= "				));\n";	
			$code1 .= "				break;\n";
			$code1 .= "				}\n";
			$code1 .= "			set_module_pref(\"uses\", get_module_pref(\"uses\") - \$l);\n";
			$code1 .= "	}else{\n";
			$code1 .= "		apply_buff('".$specialtycode."0', array(\n";
			$code1 .= "			\"startmsg\"=>\"Your attempt to use a skill failed!\",\n";
			$code1 .= "			\"rounds\"=>1,\n";
			$code1 .= "			\"schema\"=>\"specialty_".$modulename."\"\n";
			$code1 .= "		));\n";
			$code1 .= "	}\n";
			$code1 .= "}\n";
			$code1 .= "break;\n";
			$code1 .= "	case \"castlelib\":\n";
			//fix this to fix info from form
			$code1 .= "		if (\$op69 == 'tactics'){\n";
			$code1 .= "			output(\"You sit down and open up ".$bookname.".`n\");\n";
			$code1 .= "			output(\"You read for a while... in the time it takes you to read you use up`n\");\n";
			$code1 .= "			output(\"3 Turns.`n`n\");\n";
			$code1 .= "			output(\"".$bookmessage."`n\");\n";
			$code1 .= "			\$session['user']['turns']-=3;\n";
			$code1 .= "			set_module_pref('skill',(get_module_pref('skill','specialty_".$modulename."') + 1),'specialty_".$modulename."');\n";
			$code1 .= "set_module_pref('uses', get_module_pref(\"uses\",'specialty_".$modulename."') + 1,'specialty_".$modulename."');\n";
			$code1 .= "addnav(\"Continue\",\"runmodule.php?module=lonnycastle&op=library\");\n";
			$code1 .= "			}\n";
			$code1 .= "		break;\n";
			//fix this info from form
			$code1 .= "	case \"castlelibbook\":\n";
			$code1 .= "		output(\"".$bookname.". (3 Turns)`n\");\n";
			$code1 .= "		addnav(\"Read a Book\");\n";
			$code1 .= "		addnav(\"".$bookname."\",\"runmodule.php?module=lonnycastle&op=library&op69=".$modulename."\");\n";
			$code1 .= "		break;\n";
			$code1 .= "		\n";
			$code1 .= "	case \"choose-specialty\":\n";
			$code1 .= "		if (\$session['user']['dragonkills']>=get_module_setting(\"mindk\")) {\n";
			$code1 .= "			if (\$session['user']['specialty'] == \"\" ||\n";
			$code1 .= "				\$session['user']['specialty'] == '0') {\n";
			$code1 .= "				addnav(\"\$ccode\$name`0\",\"newday.php?setspecialty=\".\$spec.\"\$resline\");\n";
			$code1 .= "				\$t1 = translate_inline(\"".$specmemories."\");\n";
			$code1 .= "				\$t2 = appoencode(translate_inline(\"\$ccode\$name`0\"));\n";
			$code1 .= "				rawoutput(\"<a href='newday.php?setspecialty=\$spec\$resline'>\$t1 (\$t2)</a><br>\");\n";
			$code1 .= "				addnav(\"\",\"newday.php?setspecialty=\$spec\$resline\");\n";
			$code1 .= "			}\n";
			$code1 .= "		}\n";
			$code1 .= "		break;\n";
			$code1 .= "	case \"dragonkill\":\n";
			$code1 .= "		set_module_pref(\"uses\", 0);\n";
			$code1 .= "		set_module_pref(\"skill\", 0);\n";
			$code1 .= "		break;\n";
			$code1 .= "	case \"fightnav-specialties\":\n";
			$code1 .= "		\$uses = get_module_pref(\"uses\");\n";
			$code1 .= "		\$script = \$args['script'];\n";
			$code1 .= "		if (\$uses > 0) {\n";
			$code1 .= "addnav(array(\"%s%s (%s points)`0\", \$ccode, translate_inline(\$name), \$uses), \"\");\n";
			$code1 .= "			addnav(array(\"%s ".htmlentities("&#149;")." ".$skill1."`7 (%s)`0\", \$ccode, 1), \n";
			$code1 .= "					\$script.\"op=fight&skill=\$spec&l=1\", true);\n";
			$code1 .= "		}\n";
			$code1 .= "		if (\$uses > 1) {\n";
			$code1 .= "			addnav(array(\"%s ".htmlentities("&#149;")." ".$skill2."`7 (%s)`0\", \$ccode, 2),\n";
			$code1 .= "					\$script.\"op=fight&skill=\$spec&l=2\",true);\n";
			$code1 .= "		}\n";
			$code1 .= "		if (\$uses > 2) {\n";
			$code1 .= "			addnav(array(\"%s ".htmlentities("&#149;")." ".$skill3."`7 (%s)`0\", \$ccode, 3),\n";
			$code1 .= "					\$script.\"op=fight&skill=\$spec&l=3\",true);\n";
			$code1 .= "		}\n";
			$code1 .= "		if (\$uses > 4) {\n";
			$code1 .= "			addnav(array(\"%s ".htmlentities("&#149;")." ".$skill5."`7 (%s)`0\", \$ccode, 5),\n";
			$code1 .= "					\$script.\"op=fight&skill=\$spec&l=5\",true);\n";
			$code1 .= "		}\n";
			$code1 .= "		break;\n";
			$code1 .= "	\n";	
			$code1 .= "	case \"incrementspecialty\":\n";
			$code1 .= "		if(\$session['user']['specialty'] == \$spec) {\n";
			$code1 .= "			\$new = get_module_pref(\"skill\") + 1;\n";
			$code1 .= "			set_module_pref(\"skill\", \$new);\n";
			$code1 .= "			\$c = \$args['color'];\n";
			$code1 .= "			\$name=translate_inline(\$name);\n";
			$code1 .= "			output(\"`n%sYou gain a level in `&%s%s to `#%s%s!\",\n";
			$code1 .= "					\$c, \$name, \$c, \$new, \$c);\n";
			$code1 .= "			\$x = \$new % 3;\n";
			$code1 .= "			if (\$x == 0){\n";
			$code1 .= "				output(\"`n`^You gain an extra use point!`n\");\n";
			$code1 .= "				set_module_pref(\"uses\", get_module_pref(\"uses\") + 1);\n";
			$code1 .= "			}else{\n";
			$code1 .= "				if (3-\$x == 1) {\n";
			$code1 .= "			output(\"`n`^Only 1 more skill level until you gain an extra use point!`n\");\n";
			$code1 .= "				} else {\n";
			$code1 .= "			output(\"`n`^Only %s more skill levels until you gain an extra use point!`n\", (3-\$x));\n";
			$code1 .= "				}\n";
			$code1 .= "			}\n";
			$code1 .= "			output_notl(\"`0\");\n";
			$code1 .= "		}\n";
			$code1 .= "		break;\n";
			$code1 .= "	\n";
			$code1 .= "	case \"newday\":\n";
			$code1 .= "		\$bonus = getsetting(\"specialtybonus\", 1);\n";
			$code1 .= "		if(\$session['user']['specialty'] == \$spec) {\n";
			$code1 .= "		\$name=translate_inline(\$name);\n";
			$code1 .= "			if (\$bonus == 1) {\n";
			$code1 .= "				output(\"`n`2For being interested in %s%s`2, you receive `^1`2 extra `&%s%s`2 use for today.`n\",\$ccode,\$name,\$ccode,\$name);\n";
			$code1 .= "			} else {\n";
			$code1 .= "				output(\"`n`2For being interested in %s%s`2, you receive `^%s`2 extra `&%s%s`2 uses for today.`n\",\$ccode,\$name,\$bonus,\$ccode,\$name);\n";
			$code1 .= "			}\n";
			$code1 .= "		}\n";
			$code1 .= "		\$amt = (int)(get_module_pref(\"skill\") / 3);\n";
			$code1 .= "		if (\$session['user']['specialty'] == \$spec) \$amt++;\n";
			$code1 .= "		set_module_pref(\"uses\", \$amt);\n";
			$code1 .= "		break;\n";
			$code1 .= "	\n";
			$code1 .= "	case \"pointsdesc\":\n";
			$code1 .= "		\$cost = get_module_setting(\"cost\");\n";
			$code1 .= "		if (\$cost > 0){\n";
			$code1 .= "			\$args['count']++;\n";
			$code1 .= "			\$format = \$args['format'];\n";
			$code1 .= "			\$str = translate(\"The ".$moduletitle." Specialty is availiable upon reaching %s Dragon Kills and %s points.\");\n";
			$code1 .= "			\$str = sprintf(\$str, get_module_setting(\"mindk\"),\$cost);\n";
			$code1 .= "		}\n";
			$code1 .= "		output(\$format, \$str, true);\n";
			$code1 .= "		break;\n";
			$code1 .= "		\n";
			$code1 .= "	case \"set-specialty\":\n";
			$code1 .= "		if(\$session['user']['specialty'] == \$spec) {\n";
			$code1 .= "			page_header(\$name);\n";
			$code1 .= "			\$session['user']['donationspent'] = \$session['user']['donationspent'] + \$cost;\n";
			$code1 .= "			output(\"`7".$specstory." \");\n";
			$code1 .= "		}\n";
			$code1 .= "		break;\n";
			$code1 .= "		\n";
			$code1 .= "	case \"specialtycolor\":\n";
			$code1 .= "		\$args[\$spec] = \$ccode;\n";
			$code1 .= "		break;\n";
			$code1 .= "		\n";
			$code1 .= "	case \"specialtymodules\":\n";
			$code1 .= "		\$args[\$spec] = \"specialty_".$modulename."\";\n";
			$code1 .= "		break;\n";
			$code1 .= "		\n";
			$code1 .= "	case \"specialtynames\":\n";
			$code1 .= "		\$pointsavailable = \$session['user']['donation'] - \$session['user']['donationspent'];\n";
			$code1 .= "		if (\$session['user']['superuser'] & SU_EDIT_USERS || \$session['user']['dragonkills'] >= get_module_setting(\"mindk\") || get_module_setting(\"cost\") <= \$pointsavailable){\n";
			$code1 .= "			\$args[\$spec] = translate_inline(\$name);\n";
			$code1 .= "		}\n";
			$code1 .= "		break;\n";
			$code1 .= "		\n";
			$code1 .= "	}\n";
			$code1 .= "	return \$args;\n";
			$code1 .= "}\n";
			$code1 .= "\n";
			$code1 .= "function specialty_".$modulename."_run(){\n";
			$code1 .= "}\n";
			$code1 = nl2br($code1);
			output("<?php");
			rawoutput("<table style='width: 100%; text-align: left;' border='0' cellpadding='2' cellspacing='2'><tbody>");
			rawoutput("<tr><td style='vertical-align: top;'><code>".$code1."</code><br></td></tr></tbody></table>");
			output("?>");
rawoutput("<form method='post' action='runmodule.php?module=modulebuilder&op=specialty' name='specialtybuilder'>");
rawoutput("<input type='hidden' name='modulename' value='".$modulename."'> ");
rawoutput("<input type='hidden' name='moduletitle' value='".$moduletitle."'> ");
rawoutput("<input type='hidden' name='moduledesc' value='".$moduledesc."'> ");
rawoutput("<input type='hidden' name='specialtycode' value='".$specialtycode."'> ");
rawoutput("<input type='hidden' name='specmemories' value='".$specmemories."'> ");
rawoutput("<input type='hidden' name='specstory' value='".$specstory."'> ");
rawoutput("<input type='hidden' name='startmsg1' value='".$startmsg1."'> ");
rawoutput("<input type='hidden' name='skill1' value='".$skill1."'> ");
rawoutput("<input type='hidden' name='skill1rounds' value='".$skill1rounds."'> ");
rawoutput("<input type='hidden' name='skill1wearoff' value='".$skill1wearoff."'> ");
rawoutput("<input type='hidden' name='skill1dmgshield' value='".$skill1dmgshield."'> ");
rawoutput("<input type='hidden' name='skill1lifetap' value='".$skill1lifetap."'> ");
rawoutput("<input type='hidden' name='skill1regen' value='".$skill1regen."'> ");
rawoutput("<input type='hidden' name='skill1atkmod' value='".$skill1atkmod."'> ");
rawoutput("<input type='hidden' name='skill1defmod' value='".$skill1defmod."'> ");
rawoutput("<input type='hidden' name='skill1bguydefmod' value='".$skill1bguydefmod."'> ");
rawoutput("<input type='hidden' name='skill1effmsg' value='".$skill1effmsg."'> ");
rawoutput("<input type='hidden' name='skill1nodmg' value='".$skill1nodmg."'> ");
rawoutput("<input type='hidden' name='skill1efffail' value='".$skill1efffail."'> ");
rawoutput("<input type='hidden' name='skill1minion' value='".$skill1minion."'> ");
rawoutput("<input type='hidden' name='skill1maxbguydam' value='".$skill1maxbguydam."'> ");
rawoutput("<input type='hidden' name='startmsg2' value='".$startmsg2."'> ");
rawoutput("<input type='hidden' name='skill2' value='".$skill2."'> ");
rawoutput("<input type='hidden' name='skill2rounds' value='".$skill2rounds."'> ");
rawoutput("<input type='hidden' name='skill2wearoff' value='".$skill2wearoff."'> ");
rawoutput("<input type='hidden' name='skill2dmgshield' value='".$skill2dmgshield."'> ");
rawoutput("<input type='hidden' name='skill2lifetap' value='".$skill2lifetap."'> ");
rawoutput("<input type='hidden' name='skill2regen' value='".$skill2regen."'> ");
rawoutput("<input type='hidden' name='skill2atkmod' value='".$skill2atkmod."'> ");
rawoutput("<input type='hidden' name='skill2defmod' value='".$skill2defmod."'> ");
rawoutput("<input type='hidden' name='skill2bguydefmod' value='".$skill2bguydefmod."'> ");
rawoutput("<input type='hidden' name='skill2effmsg' value='".$skill2effmsg."'> ");
rawoutput("<input type='hidden' name='skill2nodmg' value='".$skill2nodmg."'> ");
rawoutput("<input type='hidden' name='skill2efffail' value='".$skill2efffail."'> ");
rawoutput("<input type='hidden' name='skill2minion' value='".$skill2minion."'> ");
rawoutput("<input type='hidden' name='skill2maxbguydam' value='".$skill2maxbguydam."'> ");
rawoutput("<input type='hidden' name='startmsg3' value='".$startmsg3."'> ");
rawoutput("<input type='hidden' name='skill3' value='".$skill3."'> ");
rawoutput("<input type='hidden' name='skill3rounds' value='".$skill3rounds."'> ");
rawoutput("<input type='hidden' name='skill3wearoff' value='".$skill3wearoff."'> ");
rawoutput("<input type='hidden' name='skill3dmgshield' value='".$skill3dmgshield."'> ");
rawoutput("<input type='hidden' name='skill3lifetap' value='".$skill3lifetap."'> ");
rawoutput("<input type='hidden' name='skill3regen' value='".$skill3regen."'> ");
rawoutput("<input type='hidden' name='skill3atkmod' value='".$skill3atkmod."'> ");
rawoutput("<input type='hidden' name='skill3defmod' value='".$skill3defmod."'> ");
rawoutput("<input type='hidden' name='skill3bguydefmod' value='".$skill3bguydefmod."'> ");
rawoutput("<input type='hidden' name='skill3effmsg' value='".$skill3effmsg."'> ");
rawoutput("<input type='hidden' name='skill3nodmg' value='".$skill3nodmg."'> ");
rawoutput("<input type='hidden' name='skill3efffail' value='".$skill3efffail."'> ");
rawoutput("<input type='hidden' name='skill3minion' value='".$skill3minion."'> ");
rawoutput("<input type='hidden' name='skill3maxbguydam' value='".$skill3maxbguydam."'> ");
rawoutput("<input type='hidden' name='startmsg5' value='".$startmsg5."'> ");
rawoutput("<input type='hidden' name='skill5' value='".$skill5."'> ");
rawoutput("<input type='hidden' name='skill5rounds' value='".$skill5rounds."'> ");
rawoutput("<input type='hidden' name='skill5wearoff' value='".$skill5wearoff."'> ");
rawoutput("<input type='hidden' name='skill5dmgshield' value='".$skill5dmgshield."'> ");
rawoutput("<input type='hidden' name='skill5lifetap' value='".$skill5lifetap."'> ");
rawoutput("<input type='hidden' name='skill5regen' value='".$skill5regen."'> ");
rawoutput("<input type='hidden' name='skill5atkmod' value='".$skill5atkmod."'> ");
rawoutput("<input type='hidden' name='skill5defmod' value='".$skill5defmod."'> ");
rawoutput("<input type='hidden' name='skill5bguydefmod' value='".$skill5bguydefmod."'> ");
rawoutput("<input type='hidden' name='skill5effmsg' value='".$skill5effmsg."'> ");
rawoutput("<input type='hidden' name='skill5nodmg' value='".$skill5nodmg."'> ");
rawoutput("<input type='hidden' name='skill5efffail' value='".$skill5efffail."'> ");
rawoutput("<input type='hidden' name='skill5minion' value='".$skill5minion."'> ");
rawoutput("<input type='hidden' name='skill5maxbguydam' value='".$skill5maxbguydam."'> ");
rawoutput("<input type='hidden' name='bookname' value='".$bookname."'> ");
rawoutput("<input type='hidden' name='bookmessage' value='".$bookmessage."'> ");
rawoutput("<input type='hidden' name='modulesubmit' value=''> ");
rawoutput("<input name='Submit' value='Make Changes' type='submit'></form>");
addnav("","runmodule.php?module=modulebuilder&op=specialty");
		}
?>